config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  resources :users do
    member do
      get :following, :followers, :liked_posts
    end
    collection do
      get :search
    end 
  end

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  # get '/search_user', to: 'users#search'
  # patch '/users/:id/edit', to: 'users#update'
  # get 'users/:username', to: 'users#show', as: :username

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :microposts,          only: [:create, :destroy, :index]
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]

  
  post '/ppost', to: 'microposts#create_at_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy

  # denotes user A is a follower of user B
  has_many :active_relationships, class_name:  "Relationship",
                                foreign_key: "follower_id",
                                dependent:   :destroy
  # denotes user B is followed by User A
  has_many :passive_relationships, class_name:  "Relationship",
                                foreign_key: "followed_id",
                                dependent:   :destroy 

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :micropost
  # has_many :post_likes, through: :microposts, source: :likes 

  default_scope -> { order(:name) }
                                                            
  before_save { self.email = email.downcase }
  before_save { self.username = username.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  validates :username, presence: true, length: { maximum: 20 },
    uniqueness: { case_sensitive: false }, 
    format: { with: /\A[a-zA-Z0-9]+\Z/ }
    
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false } 
  has_secure_password                 
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})", user_id: id)  
  end

  # def liked_posts
  #   post_ids = "SELECT micropost_id FROM likes
  #                    WHERE  user_id = #{id}"
  #   Micropost.where("id IN (#{post_ids})")
  # end  

  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user - deletes relationship entry
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end  

  def liked?(post)
    liked_posts.include?(post)
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy, :liked_posts]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page], per_page: 15)
  end  


  def show
    @user = User.find_by(username: params[:id])
    if @user.nil?
      redirect_to root_path
    else  
      @microposts = @user.microposts.paginate(page: params[:page])
      # render post form if current user
      @micropost = current_user.microposts.build if current_user == @user
    end  
  end 

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App #{@user.name}!
        To get started, try composing a post or check out what other users have posted."
      redirect_to user_path(@user.username)
    else
      render 'new'
    end
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to user_path(@user.username)
    else
      render 'edit'
    end
  end  

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end  

  def following
    @title = "Following"
    @user  = User.find_by(username: params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find_by(username: params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  def liked_posts
    @microposts = current_user.liked_posts.paginate(page: params[:page])
    render 'liked_posts'
  end  

  def search
    @users = User.where("name LIKE :query OR username LIKE :query", query: "%#{params[:q]}%")
    @users = @users.paginate(page: params[:page], per_page: 15)
    # render 'index'
    respond_to do |format|
      format.html { redirect_to users_path }
      format.js
    end     
  end  

  private

    def user_params
      params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
    end         

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def correct_user
      @user = User.find_by(username: params[:id])
      redirect_to(root_url) unless @user == current_user
    end     
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size = 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %> 

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
<%= gravatar_for user, 50 %>
<%= link_to "#{user.name} - #{user.username}", user_path(user.username) %>
<% if current_user.admin? && current_user != user %>
  <%= link_to "delete", user, style:"color: red; display: block", method: :delete, data: { confirm: "You sure?" } %>
<% end %>
</li>

app/views/users/edit.html.erb
<!--edit form -->
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label "Password (leave blank if unchanged)" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

<!--     <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div> -->
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1><%= link_to "All Users", users_path %></h1>

<%= form_tag(search_users_path, method: "get", class: "u_search", remote: true) do %>
  <%= text_field_tag(:q, nil, placeholder: "Search for Users") %>
  <%= submit_tag("Search", class:"btn btn-primary") %>
<% end %>

<div class = "users_paginate"><%= will_paginate %></div>

<ul class="users">
  <%= render @users %>
</ul>

<div class = "users_paginate"><%= will_paginate %></div>

app/views/users/liked_posts.html.erb
<% provide(:title, "My Liked Posts") %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for current_user %>
      <h1><%= current_user.name %></h1>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%=pluralize(@microposts.count, 'Post')%> Liked</h3>
    <% if @microposts.any? %>
      <ul class="microposts">
        <%= render @microposts %>
      </ul>
      <%= will_paginate @microposts%>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<!-- sign up form -->
<% provide(:title, "Sign Up") %>

<div class="row">
  <h1>Sign up</h1>
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label "Username (no spaces, symbols)" %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/search.js.erb
$(".users").html("<%= escape_javascript(render @users) %>");
$(".users_paginate").html("<%= escape_javascript(will_paginate @users) %>");

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <span><%=@user.username%></span>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>     
      <%= link_to("View liked posts", liked_posts_user_path(current_user.username)) if current_user == @user %>
    </section>
    <%= render 'follow_form' if logged_in? %>
    <% if @micropost %>
      <section class="micropost_form">
        <%= render 'shared/micropost_form'%>
      </section>
    <% end %>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>  
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= "#{@user.username}'s #{@title}" %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>