config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  resources :users do
    member do
      get :following, :followers, :liked_posts
    end
    collection do
      get :search
    end 
  end

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  # get '/search_user', to: 'users#search'
  # patch '/users/:id/edit', to: 'users#update'
  # get 'users/:username', to: 'users#show', as: :username

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :microposts,          only: [:create, :destroy, :index]
  resources :relationships,       only: [:create, :destroy]
  resources :likes,               only: [:create, :destroy]

  
  post '/ppost', to: 'microposts#create_at_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<ol class="microposts">
  <%= render @feed_items %>
</ol>
<%= will_paginate @feed_items %>

app/views/shared/_like.html.erb
<%= form_for(micropost.likes.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :post, micropost.id %></div>
  <%= f.submit "Like", class: "btn btn-primary btn-xs"%>
<% end %> 

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, url: microposts_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose a new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user.username) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user.username) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_unlike.html.erb
<%= form_for(micropost.likes.find_by(micropost_id: micropost.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Liked", class: "btn btn-default btn-xs"%>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, 80), user_path(current_user.username) %>
<div class = "text">
  <h3><%= current_user.name %></h3>
  <span><%= link_to "view my profile", user_path(current_user.username) %></span>
  <span><%= pluralize(current_user.microposts.count, "micropost") %></span>
</div>